ingredient_mapping = {
    'rice': ['white rice', 'brown rice', 'wild rice', 'rice'],
    'eels on rice': ['rice'],
    'pilaf': ['wild rice', 'brown rice', 'white rice', 'rice'],
    "chicken-'n'-egg on rice": ['chicken', 'eggs', 'rice'],
    'pork cutlet on rice': ['pork', 'bread'],
    'beef curry': ['beef'],
    'sushi': ['rice', 'fish', 'seaweed'],
    'chicken rice': ['chicken', 'rice'],
    'fried rice': ['fried rice', 'rice', 'eggs'],
    'tempura bowl': ['rice', 'shrimp', 'squash', 'green beans', 'bell peppers'],
    'bibimbap': ['rice', 'beef', 'spinach (raw)', 'bean sprouts', 'carrot', 'eggs'],
    'toast': ['bread'],
    'croissant': [],
    'roll bread': ['bread', 'rolls'],
    'raisin bread': ['raisin bread', 'bread'],
    'chip butty': ['potato chips', 'bread', 'butter'],
    'hamburger': ['ground beef', 'bread', 'lettuce', 'tomatoes', 'onions', 'cheese'],
    'pizza': ['cheese pizza', 'pizza', 'pepperoni', 'mushroom', 'olives'],
    'sandwiches': ['bread', 'ham', 'cheese', 'lettuce', 'tomatoes', 'mayonnaise', 'mustard'],
    'udon noodle': ['noodles'],
    'tempura udon': ['noodles', 'shrimp', 'squash', 'green beans', 'bell peppers'],
    'soba noodle': ['noodles', 'seaweed'],
    'ramen noodle': ['noodles', 'pork', 'eggs', 'seaweed', 'green onions'],
    'beef noodle': ['noodles', 'beef'],
    'tensin noodle': ['noodles', 'crab', 'eggs'],
    'fried noodle': ['fried noodle', 'noodles', 'shrimp', 'cabbage', 'carrot', 'onions'],
    'spaghetti': ['spaghetti', 'ground beef', 'cheese'],
    'Japanese-style pancake': ['pancakes', 'cabbage', 'pork'],
    'takoyaki': ['octopus', 'green onions'],
    'gratin': ['pasta', 'potatoes', 'cheese', 'bread crumbs'],
    'sauteed vegetables': ['carrot', 'broccoli', 'bell peppers', 'onions'],
    'croquette': ['potatoes', 'ground beef', 'bread crumbs', 'eggs'],
    'grilled eggplant': ['eggplant', 'oil'],
    'sauteed spinach': ['spinach (raw)', 'garlic', 'oil'],
    'vegetable tempura': ['broccoli', 'carrot', 'sweet potato', 'vegetable oil'],
    'miso soup': ['tofu', 'seaweed', 'green onions'],
    'potage': ['potatoes', 'leeks', 'carrot', 'cream'],
    'sausage': ['sausage'],
    'oden': ['eggs', 'soy sauce'],
    'omelet': ['omelets', 'eggs'],
    'ganmodoki': ['tofu', 'carrot', 'seaweed', 'soy sauce'],
    'jiaozi': ['ground pork', 'cabbage', 'chive', 'ginger', 'soy sauce'],
    'stew': ['beef', 'potatoes', 'carrots', 'celery'],
    'teriyaki grilled fish': ['fish'],
    'fried fish': ['fish', 'flour', 'oil'],
    'grilled salmon': ['salmon', 'oil', 'lemon'],
    'salmon meuniere ': ['salmon', 'butter', 'flour', 'lemon'],
    'sashimi': ['fish'],
    'grilled pacific saury ': ['fish', 'soy sauce'],
    'sukiyaki': ['beef', 'tofu', 'cabbage', 'mushroom', 'onions', 'soy sauce'],
    'sweet and sour pork': ['pork', 'bell peppers', 'onions', 'pineapple'],
    'lightly roasted fish': ['fish'],
    'steamed egg hotchpotch': ['eggs', 'chicken', 'shrimp', 'vegetables'],
    'tempura': ['shrimp', 'sweet potato', 'eggplant', 'green beans', 'vegetable oil'],
    'fried chicken': ['fried chicken', 'chicken', 'flour', 'oil'],
    'sirloin cutlet ': ['beef', 'bread crumbs', 'eggs', 'oil'],
    'nanbanzuke': ['fish', 'vinegar', 'onions', 'carrots', 'bell peppers'],
    'boiled fish': ['fish', 'soy sauce', 'ginger'],
    'seasoned beef with potatoes': ['beef', 'potatoes', 'onions', 'soy sauce'],
    'hambarg steak': ['ground beef', 'bread crumbs', 'eggs', 'onions'],
    'beef steak': ['steak', 'beef'],
    'dried fish': ['fish'],
    'ginger pork saute': ['pork', 'ginger', 'soy sauce', 'onions'],
    'spicy chili-flavored tofu': ['tofu', 'chili', 'sesame oil', 'soy sauce'],
    'yakitori': ['chicken', 'green onions'],
    'cabbage roll': ['cabbage', 'ground pork', 'rice', 'tomato'],
    'rolled omelet': ['eggs', 'soy sauce'],
    'egg sunny-side up': ['eggs'],
    'fermented soybeans': [],
    'cold tofu': ['tofu', 'soy sauce', 'green onions', 'ginger'],
    'egg roll': ['cabbage', 'carrot', 'pork', 'shrimp'],
    'chilled noodle': ['noodles', 'soy sauce', 'cucumber', 'tomatoes', 'sesame seeds'],
    'stir-fried beef and peppers': ['beef', 'bell peppers', 'onions', 'soy sauce'],
    'simmered pork': ['pork', 'soy sauce', 'ginger'],
    'boiled chicken and vegetables': ['chicken', 'carrots', 'potatoes', 'onions', 'celery'],
    'sashimi bowl': ['rice', 'fish', 'seaweed', 'soy sauce'],
    'sushi bowl': ['rice', 'fish', 'eggs', 'vegetables', 'seaweed'],
    'fish-shaped pancake with bean jam': ['pancakes'],
    'shrimp with chill source': ['shrimp', 'chili', 'garlic', 'ginger'],
    'roast chicken': ['chicken', 'rosemary', 'thyme', 'garlic', 'onions'],
    'steamed meat dumpling': ['ground pork', 'cabbage', 'ginger', 'soy sauce'],
    'omelet with fried rice': ['eggs', 'rice', 'peas', 'carrot', 'green onions'],
    'cutlet curry': ['pork', 'bread crumbs', 'egg', 'rice'],
    'spaghetti meat sauce': ['pasta', 'ground beef', 'tomato', 'onions', 'garlic', 'herbs'],
    'fried shrimp': ['shrimp', 'flour', 'eggs', 'bread crumbs', 'oil'],
    'potato salad': ['potatoes', 'mayonnaise', 'celery', 'onions', 'mustard', 'eggs'],
    'green salad': ['lettuce', 'tomatoes', 'cucumbers', 'carrots', 'salad dressing'],
    'macaroni salad': ['macaroni', 'mayonnaise', 'celery', 'onions', 'bell peppers', 'eggs'],
    'Japanese tofu and vegetable chowder': ['tofu', 'fish', 'miso', 'vegetables'],
    'pork miso soup': ['miso', 'fish', 'pork', 'onions', 'tofu'],
    'chinese soup': ['vegetables', 'meat', 'shrimp', 'soy sauce'],
    'beef bowl': ['rice', 'beef', 'onions', 'soy sauce'],
    'kinpira-style sauteed burdock': ['carrot', 'soy sauce', 'sesame oil'],
    'rice ball': ['rice', 'seaweed', 'tuna', 'pickles'],
    'pizza toast': ['bread', 'tomato', 'cheese', 'pepperoni', 'mushroom'],
    'dipping noodles': ['noodles', 'soy sauce', 'green onions', 'seaweed'],
    'hot dog': ['hot dogs', 'bread', 'mustard', 'ketchup', 'onions'],
    'french fries': ['potatoes', 'oil', 'salt'],
    'mixed rice': ['rice', 'vegetables', 'bean(seed) ', 'meat'],
    'goya chanpuru': ['tofu', 'eggs', 'pork', 'vegetables']
}